using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using System.Windows.Forms;

public static class AppPaths {
    public static readonly bool Portable=File.Exists(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"portable.flag"));
    public static readonly string Data=Portable?AppDomain.CurrentDomain.BaseDirectory:Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"SteamMonitorLauncher");
    public static string InstanceSuffix {get {if(!Portable)return "";using(var hash=System.Security.Cryptography.SHA256.Create())return ".Portable."+BitConverter.ToString(hash.ComputeHash(Encoding.UTF8.GetBytes(Data.ToUpperInvariant()))).Replace("-","").Substring(0,16);}}
}
public class GameOptions {
    public string Id="",LaunchMode="Default",LaunchPath="",Arguments="",Artwork="";
    public bool Favorite,StopAfterPlacement;
    public int DelaySeconds;
    public DateTime LastPlayed=DateTime.MinValue;
}
public class ImportEntry {
    public string Name,Executable,Arguments="",Shortcut="";
    public override string ToString(){return Name+"  |  "+Executable;}
}
public static class Gamepad {
    [StructLayout(LayoutKind.Sequential)] public struct Pad {public ushort Buttons;public byte LT,RT;public short LX,LY,RX,RY;}
    [StructLayout(LayoutKind.Sequential)] public struct State {public uint Packet;public Pad Pad;}
    [DllImport("xinput1_4.dll",EntryPoint="XInputGetState")] static extern uint Read14(uint index,out State state);
    [DllImport("xinput9_1_0.dll",EntryPoint="XInputGetState")] static extern uint Read91(uint index,out State state);
    public static ushort Buttons(){try{for(uint i=0;i<4;i++){State state;uint result;try{result=Read14(i,out state);}catch(DllNotFoundException){result=Read91(i,out state);}if(result==0){ushort b=state.Pad.Buttons;if(state.Pad.LY>16000)b|=1;if(state.Pad.LY< -16000)b|=2;return b;}}}catch{}return 0;}
}
public partial class Launcher {
    HashSet<string> recentSessions=new HashSet<string>();
    GameOptions Options(string id){var x=settings.GameOptions.FirstOrDefault(o=>o.Id==id);return x==null?new GameOptions{Id=id}:new GameOptions{Id=x.Id,Favorite=x.Favorite,LastPlayed=x.LastPlayed,Artwork=x.Artwork,DelaySeconds=x.DelaySeconds,StopAfterPlacement=x.StopAfterPlacement,LaunchMode=x.LaunchMode,LaunchPath=x.LaunchPath,Arguments=x.Arguments};}
    void StoreOptions(GameOptions option){var old=settings.GameOptions.FirstOrDefault(x=>x.Id==option.Id);if(old!=null)settings.GameOptions.Remove(old);settings.GameOptions.Add(option);if(!Save()){settings.GameOptions.Remove(option);if(old!=null)settings.GameOptions.Add(old);}gameList.Invalidate();}
    void RememberPlayed(string id){if(String.IsNullOrEmpty(id))return;var option=Options(id);option.LastPlayed=DateTime.UtcNow;StoreOptions(option);}
    void TrackSessions(List<Candidate> candidates){var ids=new HashSet<string>(candidates.Where(x=>!String.IsNullOrEmpty(x.GameId)).Select(x=>x.GameId));foreach(string id in ids)if(!recentSessions.Contains(id))RememberPlayed(id);recentSessions=ids;}
    void EditGameOptions(Game game){if(game==null)return;using(var form=ToolForm("Launch and movement: "+game.Name)){
        var body=ToolStack(form);var old=Options(game.Id);
        body.Controls.Add(new Label{Text="Startup delay before moving each new window (seconds)",Width=610,Height=25});
        var delay=new NumericUpDown{Width=180,Minimum=0,Maximum=600,Value=Math.Max(0,Math.Min(600,old.DelaySeconds))};body.Controls.Add(delay);
        var stop=new CheckBox{Text="Stop moving this window after its placement is verified",AutoSize=true,Checked=old.StopAfterPlacement};body.Controls.Add(stop);
        body.Controls.Add(new Label{Text="Launch method (Default uses the game's detected store or EXE)",Width=610,Height=30});
        var mode=new ComboBox{Width=610,DropDownStyle=ComboBoxStyle.DropDownList};mode.Items.AddRange(new object[]{"Default","Executable","Shortcut"});mode.SelectedItem=old.LaunchMode;if(mode.SelectedIndex<0)mode.SelectedIndex=0;body.Controls.Add(mode);
        var path=new TextBox{Width=610,Text=old.LaunchPath};body.Controls.Add(path);
        ToolButton(body,"Browse launch EXE or shortcut",delegate{using(var pick=new OpenFileDialog{Filter="Executable or shortcut|*.exe;*.lnk;*.url"})if(pick.ShowDialog(form)==DialogResult.OK)path.Text=pick.FileName;});
        body.Controls.Add(new Label{Text="Arguments (Executable mode only)",Width=610});var args=new TextBox{Width=610,Text=old.Arguments};body.Controls.Add(args);
        body.Controls.Add(new Label{Text="Detection still uses the registered game EXE/folder. Store shortcuts can supply login and launch tokens. New replacement windows are tracked separately.",Width=610,Height=65});
        ToolButton(body,"Save",delegate{string m=Convert.ToString(mode.SelectedItem);string ext=Path.GetExtension(path.Text).ToLowerInvariant();if(m!="Default"&&(!File.Exists(path.Text)||(m=="Executable"?ext!=".exe":ext!=".lnk"&&ext!=".url"))){MessageBox.Show(form,"Choose an existing file matching the selected launch method.");return;}StoreOptions(new GameOptions{Id=game.Id,Favorite=old.Favorite,LastPlayed=old.LastPlayed,Artwork=old.Artwork,DelaySeconds=(int)delay.Value,StopAfterPlacement=stop.Checked,LaunchMode=m,LaunchPath=path.Text,Arguments=args.Text});states.Clear();form.Close();});form.ShowDialog(this);
    }}
    void FallbackDialog(){using(var form=ToolForm("Monitor disconnect fallback")){var body=ToolStack(form);var on=new CheckBox{Text="Use a fallback when a game's target monitor is disconnected",Checked=settings.FallbackEnabled,AutoSize=true};body.Controls.Add(on);
        var choice=new ComboBox{Width=610,DropDownStyle=ComboBoxStyle.DropDownList};choice.Items.Add("Primary display");foreach(var d in Displays.All())choice.Items.Add(d);choice.SelectedIndex=0;for(int i=1;i<choice.Items.Count;i++)if(((DisplayIdentity)choice.Items[i]).Key==settings.FallbackKey)choice.SelectedIndex=i;body.Controls.Add(choice);
        body.Controls.Add(new Label{Text="The saved target is kept. When displays change, placement is checked again. If the chosen fallback is also absent, the primary display is used.",Width=610,Height=80});
        ToolButton(body,"Save",delegate{var d=choice.SelectedItem as DisplayIdentity;settings.FallbackEnabled=on.Checked;settings.FallbackKey=d==null?"":d.Key;Save();states.Clear();LoadDisplays();form.Close();});form.ShowDialog(this);
    }}
    DisplayIdentity ResolveTarget(string key,string name){var target=Displays.Resolve(key,name);if(target!=null||!settings.FallbackEnabled)return target;var list=Displays.All();return list.FirstOrDefault(d=>d.Key==settings.FallbackKey)??list.FirstOrDefault(d=>d.Screen.Primary)??list.FirstOrDefault();}
    void OpenLibraryView(){using(var form=new Form{Text="Game library - controller view",Size=new Size(1100,780),MinimumSize=new Size(850,650),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Card,ForeColor=Theme.Text,Font=new Font("Segoe UI",15),Icon=appIcon,KeyPreview=true}){
        var layout=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=3,Padding=new Padding(18)};layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,65));layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,35));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,62));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,126));form.Controls.Add(layout);
        var stores=new ComboBox{Dock=DockStyle.Fill,DropDownStyle=ComboBoxStyle.DropDownList};stores.Items.Add("All stores");foreach(string source in games.Select(x=>x.Source).Distinct().OrderBy(x=>x))stores.Items.Add(source);stores.SelectedIndex=0;layout.Controls.Add(stores,0,0);
        var sort=new ComboBox{Dock=DockStyle.Fill,DropDownStyle=ComboBoxStyle.DropDownList};sort.Items.AddRange(new object[]{"All games","Favorites","Recently played"});sort.SelectedIndex=0;layout.Controls.Add(sort,1,0);
        var list=new ListBox{Dock=DockStyle.Fill,ItemHeight=44,IntegralHeight=false,BackColor=Theme.Raised,ForeColor=Theme.Text};layout.Controls.Add(list,0,1);
        var art=new PictureBox{Dock=DockStyle.Fill,SizeMode=PictureBoxSizeMode.Zoom,BackColor=Theme.Background};layout.Controls.Add(art,1,1);
        var buttons=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=true};layout.Controls.Add(buttons,0,2);layout.SetColumnSpan(buttons,2);
        Action reload=delegate{string selected=list.SelectedItem is Game?((Game)list.SelectedItem).Id:"";var items=games.Where(g=>stores.SelectedIndex==0||g.Source==Convert.ToString(stores.SelectedItem));if(sort.SelectedIndex==1)items=items.Where(g=>Options(g.Id).Favorite);if(sort.SelectedIndex==2)items=items.Where(g=>Options(g.Id).LastPlayed!=DateTime.MinValue).OrderByDescending(g=>Options(g.Id).LastPlayed);else items=items.OrderBy(g=>g.Name);list.BeginUpdate();list.Items.Clear();foreach(var g in items)list.Items.Add(g);for(int i=0;i<list.Items.Count;i++)if(((Game)list.Items[i]).Id==selected)list.SelectedIndex=i;if(list.SelectedIndex<0&&list.Items.Count>0)list.SelectedIndex=0;list.EndUpdate();};
        var fav=new ModernButton{Text="Favorite",Width=185,Height=46};
        Action showArt=delegate{if(art.Image!=null){var image=art.Image;art.Image=null;image.Dispose();}var g=list.SelectedItem as Game;fav.Text=g!=null&&Options(g.Id).Favorite?"Unfavorite (Y)":"Favorite (Y)";if(g==null)return;string file=Options(g.Id).Artwork;if(String.IsNullOrEmpty(file))return;try{string full=Path.IsPathRooted(file)?file:Path.Combine(Data,file);using(var image=Image.FromFile(full))art.Image=new Bitmap(image);}catch{}};
        Action launch=delegate{var game=list.SelectedItem as Game;if(game==null)return;LaunchGame(game);};
        var play=new ModernButton{Text="Play (A / Enter)",Width=220,Height=46,Primary=true};play.Click+=delegate{launch();};buttons.Controls.Add(play);
        fav.Click+=delegate{var g=list.SelectedItem as Game;if(g==null)return;var option=Options(g.Id);option.Favorite=!option.Favorite;StoreOptions(option);reload();showArt();};buttons.Controls.Add(fav);
        var cover=new ModernButton{Text="Set artwork",Width=185,Height=46};cover.Click+=delegate{var g=list.SelectedItem as Game;if(g==null)return;using(var picker=new OpenFileDialog{Filter="Artwork|*.png;*.jpg;*.jpeg;*.bmp"})if(picker.ShowDialog(form)==DialogResult.OK)try{if(new FileInfo(picker.FileName).Length>20*1024*1024)throw new InvalidDataException("Choose an image smaller than 20 MB.");Directory.CreateDirectory(Path.Combine(Data,"artwork"));string relative=Path.Combine("artwork",Guid.NewGuid().ToString("N")+".png");using(var original=Image.FromFile(picker.FileName))using(var thumbnail=new Bitmap(original,new Size(400,560)))thumbnail.Save(Path.Combine(Data,relative),System.Drawing.Imaging.ImageFormat.Png);var option=Options(g.Id);option.Artwork=relative;StoreOptions(option);showArt();}catch(Exception ex){MessageBox.Show(form,ex.Message);}};buttons.Controls.Add(cover);
        var close=new ModernButton{Text="Back (B / Esc)",Width=190,Height=46};close.Click+=delegate{form.Close();};buttons.Controls.Add(close);
        buttons.Controls.Add(new Label{Text="D-pad / stick: select  |  LB: store  |  RB: favorites/recent",AutoSize=true});
        stores.SelectedIndexChanged+=delegate{reload();};sort.SelectedIndexChanged+=delegate{reload();};list.SelectedIndexChanged+=delegate{showArt();};list.DoubleClick+=delegate{launch();};form.KeyDown+=delegate(object sender,KeyEventArgs e){if(e.KeyCode==Keys.Enter){launch();e.SuppressKeyPress=true;}if(e.KeyCode==Keys.Escape)form.Close();};reload();
        ushort previous=0;bool active=false;var padTimer=new System.Windows.Forms.Timer{Interval=100};padTimer.Tick+=delegate{ushort b=Gamepad.Buttons();if(GetForegroundWindow()!=form.Handle){previous=b;active=false;return;}if(!active){active=true;previous=b;return;}ushort pressed=(ushort)(b&~previous);previous=b;if((pressed&1)!=0&&list.Items.Count>0)list.SelectedIndex=Math.Max(0,list.SelectedIndex-1);if((pressed&2)!=0&&list.Items.Count>0)list.SelectedIndex=Math.Min(list.Items.Count-1,list.SelectedIndex+1);if((pressed&0x1000)!=0)launch();if((pressed&0x2000)!=0)form.Close();if((pressed&0x8000)!=0)fav.PerformClick();if((pressed&0x100)!=0)stores.SelectedIndex=(stores.SelectedIndex+1)%stores.Items.Count;if((pressed&0x200)!=0)sort.SelectedIndex=(sort.SelectedIndex+1)%sort.Items.Count;};padTimer.Start();form.ShowDialog(this);padTimer.Stop();padTimer.Dispose();if(art.Image!=null)art.Image.Dispose();
    }}
    void ScanFolders(){using(var pick=new FolderBrowserDialog{Description="Choose a games folder. You will review EXEs before importing."}){if(pick.ShowDialog(this)!=DialogResult.OK)return;string root=pick.SelectedPath;using(var form=ToolForm("Scan and import games")){
        var list=new CheckedListBox{Dock=DockStyle.Fill,CheckOnClick=true,HorizontalScrollbar=true,BackColor=Theme.Raised,ForeColor=Theme.Text};var label=new Label{Dock=DockStyle.Top,Height=60,Text="Scanning... No files will be launched. Close this window to cancel."};var add=Btn("Import checked game EXEs",delegate{ImportGames(list.CheckedItems.Cast<ImportEntry>().ToList());form.Close();});add.Dock=DockStyle.Bottom;add.Enabled=false;form.Controls.Add(list);form.Controls.Add(label);form.Controls.Add(add);
        var scan=new BackgroundWorker{WorkerSupportsCancellation=true};scan.DoWork+=delegate(object sender,DoWorkEventArgs e){var found=new List<ImportEntry>();var pending=new Queue<string>();pending.Enqueue(root);int folders=0,skipped=0;while(pending.Count>0&&folders<3000&&found.Count<1000&&!scan.CancellationPending){string folder=pending.Dequeue();folders++;try{foreach(string exe in Directory.GetFiles(folder,"*.exe")){string name=Path.GetFileNameWithoutExtension(exe);if(new[]{"unins","setup","install","vcredist","dxsetup","crashreport","crashpad"}.Any(x=>name.ToLowerInvariant().StartsWith(x)))continue;found.Add(new ImportEntry{Name=name,Executable=exe});if(found.Count>=1000)break;}foreach(string sub in Directory.GetDirectories(folder))if((File.GetAttributes(sub)&FileAttributes.ReparsePoint)==0)pending.Enqueue(sub);}catch{skipped++;}}e.Result=new object[]{found,"Choose actual game EXEs (not installers or launcher clients). "+found.Count+" candidates; "+skipped+" unreadable folders."+(pending.Count>0?" Scan limit reached; scan a smaller folder for more.":"")};};
        scan.RunWorkerCompleted+=delegate(object sender,RunWorkerCompletedEventArgs e){if(!form.IsDisposed){if(e.Error!=null)label.Text=e.Error.Message;else{var result=(object[])e.Result;foreach(var item in (List<ImportEntry>)result[0])list.Items.Add(item,false);label.Text=(string)result[1];add.Enabled=true;}}scan.Dispose();};form.FormClosing+=delegate{if(scan.IsBusy)scan.CancelAsync();};scan.RunWorkerAsync();form.ShowDialog(this);
    }}}
    static string ComText(object target,string property){return Convert.ToString(target.GetType().InvokeMember(property,BindingFlags.GetProperty,null,target,null));}
    void ImportShortcuts(){using(var pick=new OpenFileDialog{Filter="Windows shortcuts (*.lnk)|*.lnk",Multiselect=true,InitialDirectory=Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory),Title="Select desktop or Start Menu game shortcuts"}){if(pick.ShowDialog(this)!=DialogResult.OK)return;var entries=new List<ImportEntry>();foreach(string path in pick.FileNames){object shell=null,shortcut=null;try{shell=Activator.CreateInstance(Type.GetTypeFromProgID("WScript.Shell"));shortcut=shell.GetType().InvokeMember("CreateShortcut",BindingFlags.InvokeMethod,null,shell,new object[]{path});string target=Environment.ExpandEnvironmentVariables(ComText(shortcut,"TargetPath"));if(!File.Exists(target)||!target.EndsWith(".exe",StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("Shortcut does not point to a readable EXE. Add the game EXE manually, then choose Shortcut in Launch options.");entries.Add(new ImportEntry{Name=Path.GetFileNameWithoutExtension(path),Executable=target,Arguments=ComText(shortcut,"Arguments"),Shortcut=path});}catch(Exception ex){MessageBox.Show(this,Path.GetFileName(path)+": "+ex.Message);}finally{if(shortcut!=null)Marshal.FinalReleaseComObject(shortcut);if(shell!=null)Marshal.FinalReleaseComObject(shell);}}if(entries.Count>0)using(var form=ToolForm("Review shortcut imports")){var list=new CheckedListBox{Dock=DockStyle.Fill,CheckOnClick=true,HorizontalScrollbar=true};foreach(var entry in entries)list.Items.Add(entry,false);var help=new Label{Dock=DockStyle.Top,Height=75,Text="Check shortcuts that target the actual game EXE. For store-client shortcuts, add the actual game EXE first and set this shortcut in Launch and movement options."};var add=Btn("Import checked shortcuts",delegate{ImportGames(list.CheckedItems.Cast<ImportEntry>().ToList());form.Close();});add.Dock=DockStyle.Bottom;form.Controls.Add(list);form.Controls.Add(help);form.Controls.Add(add);form.ShowDialog(this);}}}
    void ImportGames(List<ImportEntry> entries){var added=new List<CustomGame>();var options=new List<GameOptions>();foreach(var item in entries){if(settings.CustomGames.Any(x=>String.Equals(x.Executable,item.Executable,StringComparison.OrdinalIgnoreCase)))continue;var game=new CustomGame{Id="custom:"+Guid.NewGuid().ToString("N"),Name=item.Name,Executable=item.Executable,Arguments=item.Arguments};settings.CustomGames.Add(game);added.Add(game);if(item.Shortcut.Length>0){var option=new GameOptions{Id=game.Id,LaunchMode="Shortcut",LaunchPath=item.Shortcut};settings.GameOptions.Add(option);options.Add(option);}}if(!Save()){foreach(var g in added)settings.CustomGames.Remove(g);foreach(var o in options)settings.GameOptions.Remove(o);return;}CatalogChanged();Say(added.Count+" game(s) imported. Duplicate custom EXEs were skipped.");}
    void ExportReport(){using(var picker=new SaveFileDialog{Filter="Troubleshooting report|*.txt",FileName="SteamMonitor-report.txt"})if(picker.ShowDialog(this)==DialogResult.OK)try{var text=new StringBuilder();text.AppendLine("Steam Monitor 1.12.3 diagnostics | "+DateTime.Now.ToString("s"));text.AppendLine("Mode: "+(AppPaths.Portable?"Portable":"Installed"));text.AppendLine("OS: "+Environment.OSVersion+" | CLR: "+Environment.Version);text.AppendLine("Enabled: "+settings.Enabled+" | Fallback: "+settings.FallbackEnabled+" | Target: "+settings.Monitor);foreach(var d in Displays.All())text.AppendLine("Display: "+d.Screen.DeviceName+" "+d.Screen.Bounds);foreach(var c in lastCandidates){WindowState state;text.AppendLine(c.Game+" | PID "+c.Pid+" | "+c.Title+" | "+(states.TryGetValue(c.Handle,out state)?state.Status:"Detected"));}string log=Path.Combine(Diagnostics.Folder,"watcher.log");if(File.Exists(log)){text.AppendLine("Recent watcher log:");foreach(string line in File.ReadLines(log).Reverse().Take(250).Reverse())text.AppendLine(line);}File.WriteAllText(picker.FileName,text.ToString());MessageBox.Show(this,"Report saved. Review it before sharing: it contains game names, window titles and potentially local paths.");}catch(Exception ex){MessageBox.Show(this,ex.Message);}}
    void RecoverSettings(){string folder=Path.Combine(Data,"backups");Directory.CreateDirectory(folder);using(var picker=new OpenFileDialog{Filter="Settings backup|*.xml",InitialDirectory=folder,Title="Restore an automatic settings backup"})if(picker.ShowDialog(this)==DialogResult.OK)RestoreSettingsFile(picker.FileName);}
    void RestoreSettingsFile(string path){try{var replacement=ReadBackup(path);if(MessageBox.Show(this,"Restore this settings backup? Current settings will be backed up first.","Settings recovery",MessageBoxButtons.OKCancel)!=DialogResult.OK)return;var old=settings;settings=replacement;if(!Save()){settings=old;return;}NormalizeSettings(settings);loading=true;enabled.Checked=settings.Enabled;border.Checked=settings.Borderless;loading=false;states.Clear();CatalogChanged();LoadDisplays();RegisterKeys();Say("Settings restored. Windows startup registration was not changed.");}catch(Exception ex){MessageBox.Show(this,ex.Message);}}
}
